name: trim
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^3.0.0
  responsive_builder: ^0.3.0
  device_preview: ^0.7.1
  responsive_flutter:
  curved_navigation_bar:
  http: ^0.13.1
  intl:
  google_maps_flutter:
  location:
  flutter_polyline_points: ^0.2.6
  dio: ^4.0.0   
  flutter_checkout_payment: ^1.0.0
  flutter_conditional_rendering: ^2.0.0


 



    


  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_credit_card: ^2.0.0
  scrollable_positioned_list: ^0.1.10
  badges: ^1.2.0
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  loadmore: ^2.0.1
  flutter_easyrefresh: ^2.2.1
  fluttertoast: ^8.0.6
  custom_refresh_indicator: ^0.9.0
  flutter_cache_manager: ^3.0.1
  code_fields: ^0.0.3
  flutter_verification_code: ^1.0.3
  shared_preferences: ^2.0.5
  maps_launcher: ^2.0.0
  image_picker: ^0.7.4

dev_dependencies:
  change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
